const path = require('path')
// console.log(path.basename("D:\github\node-jk\path/path.js"))
// console.log(path.basename("D:\github\node-jk\path"))
// console.log(process.env.PATH)
// console.log(path.extname("path.js"))
// console.log(path.parse(__dirname))
// console.log(path.parse(__filename))
console.log(process)